//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yillar", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSonuclar")]
    [System.SerializableAttribute()]
    public partial class Yillar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationForm.ServiceReference1.Sonuclar[] SonuclarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YilAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YilIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationForm.ServiceReference1.Sonuclar[] Sonuclar {
            get {
                return this.SonuclarField;
            }
            set {
                if ((object.ReferenceEquals(this.SonuclarField, value) != true)) {
                    this.SonuclarField = value;
                    this.RaisePropertyChanged("Sonuclar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YilAdi {
            get {
                return this.YilAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.YilAdiField, value) != true)) {
                    this.YilAdiField = value;
                    this.RaisePropertyChanged("YilAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YilId {
            get {
                return this.YilIdField;
            }
            set {
                if ((this.YilIdField.Equals(value) != true)) {
                    this.YilIdField = value;
                    this.RaisePropertyChanged("YilId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sonuclar", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSonuclar")]
    [System.SerializableAttribute()]
    public partial class Sonuclar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OgrenciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationForm.ServiceReference1.Ogrenciler OgrencilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SonucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SonucIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TurIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationForm.ServiceReference1.Turler TurlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YilIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationForm.ServiceReference1.Yillar YillarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OgrenciId {
            get {
                return this.OgrenciIdField;
            }
            set {
                if ((this.OgrenciIdField.Equals(value) != true)) {
                    this.OgrenciIdField = value;
                    this.RaisePropertyChanged("OgrenciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationForm.ServiceReference1.Ogrenciler Ogrenciler {
            get {
                return this.OgrencilerField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrencilerField, value) != true)) {
                    this.OgrencilerField = value;
                    this.RaisePropertyChanged("Ogrenciler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((this.SonucField.Equals(value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SonucId {
            get {
                return this.SonucIdField;
            }
            set {
                if ((this.SonucIdField.Equals(value) != true)) {
                    this.SonucIdField = value;
                    this.RaisePropertyChanged("SonucId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TurId {
            get {
                return this.TurIdField;
            }
            set {
                if ((this.TurIdField.Equals(value) != true)) {
                    this.TurIdField = value;
                    this.RaisePropertyChanged("TurId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationForm.ServiceReference1.Turler Turler {
            get {
                return this.TurlerField;
            }
            set {
                if ((object.ReferenceEquals(this.TurlerField, value) != true)) {
                    this.TurlerField = value;
                    this.RaisePropertyChanged("Turler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YilId {
            get {
                return this.YilIdField;
            }
            set {
                if ((this.YilIdField.Equals(value) != true)) {
                    this.YilIdField = value;
                    this.RaisePropertyChanged("YilId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationForm.ServiceReference1.Yillar Yillar {
            get {
                return this.YillarField;
            }
            set {
                if ((object.ReferenceEquals(this.YillarField, value) != true)) {
                    this.YillarField = value;
                    this.RaisePropertyChanged("Yillar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ogrenciler", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSonuclar")]
    [System.SerializableAttribute()]
    public partial class Ogrenciler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OgrenciAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OgrenciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OngrenciTcknField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationForm.ServiceReference1.Sonuclar[] SonuclarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenciAd {
            get {
                return this.OgrenciAdField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrenciAdField, value) != true)) {
                    this.OgrenciAdField = value;
                    this.RaisePropertyChanged("OgrenciAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgrenciId {
            get {
                return this.OgrenciIdField;
            }
            set {
                if ((this.OgrenciIdField.Equals(value) != true)) {
                    this.OgrenciIdField = value;
                    this.RaisePropertyChanged("OgrenciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OngrenciTckn {
            get {
                return this.OngrenciTcknField;
            }
            set {
                if ((this.OngrenciTcknField.Equals(value) != true)) {
                    this.OngrenciTcknField = value;
                    this.RaisePropertyChanged("OngrenciTckn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationForm.ServiceReference1.Sonuclar[] Sonuclar {
            get {
                return this.SonuclarField;
            }
            set {
                if ((object.ReferenceEquals(this.SonuclarField, value) != true)) {
                    this.SonuclarField = value;
                    this.RaisePropertyChanged("Sonuclar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Turler", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSonuclar")]
    [System.SerializableAttribute()]
    public partial class Turler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationForm.ServiceReference1.Sonuclar[] SonuclarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationForm.ServiceReference1.Sonuclar[] Sonuclar {
            get {
                return this.SonuclarField;
            }
            set {
                if ((object.ReferenceEquals(this.SonuclarField, value) != true)) {
                    this.SonuclarField = value;
                    this.RaisePropertyChanged("Sonuclar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TurAd {
            get {
                return this.TurAdField;
            }
            set {
                if ((object.ReferenceEquals(this.TurAdField, value) != true)) {
                    this.TurAdField = value;
                    this.RaisePropertyChanged("TurAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurId {
            get {
                return this.TurIdField;
            }
            set {
                if ((this.TurIdField.Equals(value) != true)) {
                    this.TurIdField = value;
                    this.RaisePropertyChanged("TurId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetYillars", ReplyAction="http://tempuri.org/IService1/GetYillarsResponse")]
        WebApplicationForm.ServiceReference1.Yillar[] GetYillars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetYillars", ReplyAction="http://tempuri.org/IService1/GetYillarsResponse")]
        System.Threading.Tasks.Task<WebApplicationForm.ServiceReference1.Yillar[]> GetYillarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTurlers", ReplyAction="http://tempuri.org/IService1/GetTurlersResponse")]
        WebApplicationForm.ServiceReference1.Turler[] GetTurlers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTurlers", ReplyAction="http://tempuri.org/IService1/GetTurlersResponse")]
        System.Threading.Tasks.Task<WebApplicationForm.ServiceReference1.Turler[]> GetTurlersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOgrencilers", ReplyAction="http://tempuri.org/IService1/GetOgrencilersResponse")]
        WebApplicationForm.ServiceReference1.Ogrenciler[] GetOgrencilers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOgrencilers", ReplyAction="http://tempuri.org/IService1/GetOgrencilersResponse")]
        System.Threading.Tasks.Task<WebApplicationForm.ServiceReference1.Ogrenciler[]> GetOgrencilersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplicationForm.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplicationForm.ServiceReference1.IService1>, WebApplicationForm.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplicationForm.ServiceReference1.Yillar[] GetYillars() {
            return base.Channel.GetYillars();
        }
        
        public System.Threading.Tasks.Task<WebApplicationForm.ServiceReference1.Yillar[]> GetYillarsAsync() {
            return base.Channel.GetYillarsAsync();
        }
        
        public WebApplicationForm.ServiceReference1.Turler[] GetTurlers() {
            return base.Channel.GetTurlers();
        }
        
        public System.Threading.Tasks.Task<WebApplicationForm.ServiceReference1.Turler[]> GetTurlersAsync() {
            return base.Channel.GetTurlersAsync();
        }
        
        public WebApplicationForm.ServiceReference1.Ogrenciler[] GetOgrencilers() {
            return base.Channel.GetOgrencilers();
        }
        
        public System.Threading.Tasks.Task<WebApplicationForm.ServiceReference1.Ogrenciler[]> GetOgrencilersAsync() {
            return base.Channel.GetOgrencilersAsync();
        }
    }
}
