//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceSonuclar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinavSonuclariEntities : DbContext
    {
        public SinavSonuclariEntities()
            : base("name=SinavSonuclariEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ogrenciler> Ogrenciler { get; set; }
        public virtual DbSet<Sonuclar> Sonuclar { get; set; }
        public virtual DbSet<Turler> Turler { get; set; }
        public virtual DbSet<Yillar> Yillar { get; set; }
    }
}
