//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceSonuclar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonuclar
    {
        public int SonucId { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<int> TurId { get; set; }
        public Nullable<int> YilId { get; set; }
        public Nullable<int> Sonuc { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual Turler Turler { get; set; }
        public virtual Yillar Yillar { get; set; }
    }
}
